// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'app/model/api_data_model/data_result_model.dart';
import 'app/model/bluetooth_printer.dart';
import 'app/model/cart/cart_model.dart';
import 'app/model/login/login_data_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BluetoothPrinterAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(CategoryTreeProductAdapter());
    registerAdapter(CompanyInfoAdapter());
    registerAdapter(DataResultModelAdapter());
    registerAdapter(DsnAdapter());
    registerAdapter(LoginDataModelAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductRemarkAdapter());
    registerAdapter(SetMealListAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BluetoothPrinterAdapter());
    registerAdapter(CartModelAdapter());
    registerAdapter(CategoryTreeProductAdapter());
    registerAdapter(CompanyInfoAdapter());
    registerAdapter(DataResultModelAdapter());
    registerAdapter(DsnAdapter());
    registerAdapter(LoginDataModelAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductRemarkAdapter());
    registerAdapter(SetMealListAdapter());
  }
}
