// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kiosk_plus/app/model/api_data_model/data_result_model.dart';
import 'package:kiosk_plus/app/model/login/login_data_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryTreeProductAdapter());
    registerAdapter(DataResultModelAdapter());
    registerAdapter(DsnAdapter());
    registerAdapter(LoginDataModelAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductRemarkAdapter());
    registerAdapter(ProductSetMealAdapter());
    registerAdapter(ProductSetMealLimitAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryTreeProductAdapter());
    registerAdapter(DataResultModelAdapter());
    registerAdapter(DsnAdapter());
    registerAdapter(LoginDataModelAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductRemarkAdapter());
    registerAdapter(ProductSetMealAdapter());
    registerAdapter(ProductSetMealLimitAdapter());
  }
}
